package mangadex

import (
	"context"
	"fmt"
	"github.com/Fesaa/Media-Provider/db/models"
	"github.com/Fesaa/Media-Provider/http/menou"
	"github.com/Fesaa/Media-Provider/http/payload"
	"github.com/Fesaa/Media-Provider/providers/pasloe/core"
	"github.com/Fesaa/Media-Provider/services"
	"github.com/Fesaa/Media-Provider/utils"
	"github.com/spf13/afero"
	"go.uber.org/dig"
	"slices"
)

const comicInfoNote = "This comicinfo.xml was auto generated by Media-Provider, with information from mangadex. Source code can be found here: https://github.com/Fesaa/Media-Provider/"
const metronInfoNote = "This metroninfo.xml was auto generated by Media-Provider, with information from mangadex. Source code can be found here: https://github.com/Fesaa/Media-Provider/"
const timeLayout = "2006-01-02T15:04:05Z07:00"
const genreTag = "genre"

func NewManga(scope *dig.Scope) core.Downloadable {
	var m *manga

	utils.Must(scope.Invoke(func(
		req payload.DownloadRequest, httpClient *menou.Client,
		repository Repository, markdownService services.MarkdownService,
		imageService services.ImageService, archiveService services.ArchiveService,
		fs afero.Afero,
	) {
		m = &manga{
			id:              req.Id,
			httpClient:      httpClient,
			repository:      repository,
			markdownService: markdownService,
			imageService:    imageService,
			archiveService:  archiveService,
			fs:              fs,

			language: utils.MustHave(req.GetString(LanguageKey, "en")),
		}
		m.Core = core.New[ChapterSearchData](scope, "mangadex", m)
	}))

	return m
}

type manga struct {
	*core.Core[ChapterSearchData]
	id string

	httpClient      *menou.Client
	repository      Repository
	markdownService services.MarkdownService
	imageService    services.ImageService
	archiveService  services.ArchiveService
	fs              afero.Afero

	info     *MangaSearchData
	chapters ChapterSearchResponse

	coverFactory CoverFactory

	lastFoundChapter int
	lastFoundVolume  int
	foundLastVolume  bool
	foundLastChapter bool

	hasWarned          bool
	hasWarnedBlacklist bool
	hasNotifiedSub     bool

	language string
}

func (m *manga) Title() string {
	if m.info == nil {
		if m.TempTitle != "" {
			return m.TempTitle
		}

		return m.id
	}

	return m.info.Attributes.LangTitle(m.language)
}

func (m *manga) Provider() models.Provider {
	return m.Req.Provider
}

func (m *manga) RefUrl() string {
	if m.info == nil {
		return fmt.Sprintf("https://mangadex.org/title/%s/", m.Id())
	}

	return m.info.RefURL()
}

func (m *manga) All() []ChapterSearchData {
	return m.chapters.Data
}

func (m *manga) ContentList() []payload.ListContentData {
	if len(m.chapters.Data) == 0 {
		return nil
	}

	data := utils.GroupBy(m.chapters.Data, func(v ChapterSearchData) string {
		return v.Attributes.Volume
	})

	childrenFunc := func(chapters []ChapterSearchData) []payload.ListContentData {
		slices.SortFunc(chapters, func(a, b ChapterSearchData) int {
			if a.Attributes.Volume != b.Attributes.Volume {
				return (int)(b.Volume() - a.Volume())
			}
			return (int)(b.Chapter() - a.Chapter())
		})

		return utils.Map(chapters, func(chapter ChapterSearchData) payload.ListContentData {
			return payload.ListContentData{
				SubContentId: chapter.Id,
				Selected:     len(m.ToDownloadUserSelected) == 0 || slices.Contains(m.ToDownloadUserSelected, chapter.Id),
				Label: utils.Ternary(chapter.Attributes.Title == "",
					m.Title()+" "+chapter.Label(),
					chapter.Label()),
			}
		})
	}

	sortSlice := utils.Keys(data)
	slices.SortFunc(sortSlice, utils.SortFloats)

	out := make([]payload.ListContentData, 0, len(data))
	for _, volume := range sortSlice {
		chapters := data[volume]

		// Do not add No Volume label if there are no volumes
		if volume == "" && len(sortSlice) == 1 {
			out = append(out, childrenFunc(chapters)...)
			continue
		}

		out = append(out, payload.ListContentData{
			Label:    utils.Ternary(volume == "", "No Volume", fmt.Sprintf("Volume %s", volume)),
			Children: childrenFunc(chapters),
		})
	}
	return out
}

func (m *manga) ContentUrls(ctx context.Context, chapter ChapterSearchData) ([]string, error) {
	imageInfo, err := m.repository.GetChapterImages(ctx, chapter.Id)
	if err != nil {
		return nil, err
	}
	return imageInfo.FullImageUrls(), nil
}

func (m *manga) volumeDir(v string) string {
	if v == "" {
		return fmt.Sprintf("%s Special", m.Title())
	}

	return fmt.Sprintf("%s Vol. %s", m.Title(), v)
}
