name: Test 3rd party requests

on:
  push:
    branches:
      - "master"
    paths:
      - "yts/**"
      - "limetorrents/**"
      - ".github/workflow/request_tests.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Test YTS
        run: go test -v ./yts

      - name: Test Lime
        run: go test -v ./limetorrents

      - name: Test Subs Please
        run: go test -v ./subsplease