name: Run Tests

on:
  pull_request:
    branches:
      - "master"
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.2"

      - name: Test YTS
        run: go test -v ./providers/yoitsu/yts

      - name: Test Lime
        run: go test -v ./providers/yoitsu/limetorrents

      - name: Test Subs Please
        run: go test -v ./providers/yoitsu/subsplease

      - name: Mangadex test
        run: go test -v ./providers/mangadex
