name: Validate - Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: 🧪 Test
        run: go test -v ./...