name: Validate - Tests

on:
  pull_request:
    branches:
      - master
  workflow_call:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.1

      - name: Install libwebp-dev
        run: sudo apt-get update && sudo apt-get install -y libwebp-dev

      - name: 🧪 Test
        run: go test -v ./...